- name: Ensure basic packages are installed
  apt:
    name: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    state: present
    update_cache: yes

- name: Users
  include: users.yml

- name: SSH
  include: ssh.yml