- name: Create the entrypoint for my main user account
  user:
    name: "{{ user }}"
    home: "{{ home }}"
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: "on_create"
    shell: /bin/bash
    system: true
  become: true

- name: Give user sudo access
  lineinfile:
    path: /etc/sudoers
    line: "{{ user }} ALL=(ALL) ALL"
  become: true