- name: Create install directory
  file:
    path: /opt/traefik
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/traefik/docker-compose.yml
    owner: "{{ user }}"
    group: "{{ user }}"
  notify: restart traefik
  become: true

- name: Copy over required files
  template:
    src: files/traefik.yml
    dest: /opt/traefik/traefik.yml
    owner: "{{ user }}"
    group: "{{ user }}"
  notify: restart traefik
  become: true

- name: Copy over required files
  template:
    src: files/env
    dest: /opt/traefik/.env
    owner: "{{ user }}"
    group: "{{ user }}"
  notify: restart traefik
  become: true

- name: Copy over required files
  template:
    src: files/static.yml
    dest: /opt/traefik/static.yml
    owner: "{{ user }}"
    group: "{{ user }}"
  notify: restart traefik
  become: true

- name: Ensure acme.json exists
  file:
    path: /opt/traefik/acme.json
    state: touch
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '600'
  become: true
  changed_when: false