version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - /opt/firefly/upload:/var/www/html/storage/upload
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.fireflyiii.rule=Host(`finance.lvk.sh`)
      - traefik.http.routers.fireflyiii.tls=true
      - traefik.http.routers.fireflyiii.service=fireflyiii
      - traefik.http.services.fireflyiii.loadbalancer.server.port=8080
      - traefik.http.routers.fireflyiii.tls.domains[0].main=lvk.sh
      - traefik.http.routers.fireflyiii.tls.domains[0].sans=*.lvk.sh
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    env_file: .env
    volumes:
      - /opt/firefly/db:/var/lib/mysql