version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.fireflyiii.rule=Host(`finance.lvk.sh`)
      - traefik.http.routers.fireflyiii.tls=true
      - traefik.http.routers.fireflyiii.service=fireflyiii
      - traefik.http.services.fireflyiii.loadbalancer.server.port=8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: yobasystems/alpine-mariadb:latest
    env_file: .env
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_upload:
   firefly_iii_db: