version: "2"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - TZ=Europe/London
      - GF_DATABASE_URL=postgres://grafana:grafana@db/grafana
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - ./data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - db
      - renderer
    networks:
      - default
      - grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.lvk.sh`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.services.grafana.loadbalancer.server.port=3000
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_USER=grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    restart: unless-stopped
    environment:
      - BROWSER_TZ=Europe/London

networks:
  grafana:
    external: true