---
- name: Base System Configuration
  hosts: all
  roles:
    - role: base
      become: true

- name: Install Docker
  hosts:
  - zeus
  roles:
  - docker

- name: Install Traefik
  hosts:
  - zeus
  roles:
  - traefik

- name: Setup Finance
  hosts:
  - zeus
  roles:
  - firefly

- name: Setup Monitoring
  hosts:
  - zeus
  - hermes
  roles:
  - grafana
  - influxdb


- name: Setup Siren
  hosts:
  - zeus
  roles:
  - siren