http:
  routers:
    dashboard:
      rule: Host(`traefik.lucemans.com`)
      service: api@internal
      tls:
        certResolver: letsencrypt
    dashboard2:
      rule: Host(`hermes.lvk.sh`)
      service: api@internal
      tls:
        certResolver: letsencrypt
    pterodactylnode:
      rule: Host(`node.lvk.sh`)
      service: pterodactylnode
      tls:
        certResolver: letsencrypt
    jitsi:
      rule: Host(`meet.lvk.sh`)
      service: jitsi
      tls:
        certResolver: letsencrypt
    plausible:
      rule: Host(`plausible.lvk.sh`)
      service: plausible
      tls:
        certResolver: letsencrypt
    fdynmap:
      rule: Host(`dynmap.florisvk.be`)
      service: fdynmap
      tls:
        certResolver: letsencrypt
  services:
    plausible:
      loadBalancer:
        servers:
          - url: "http://localhost:8001/"
    pterodactylnode:
      loadBalancer:
        servers:
          - url: "http://localhost:8081/"
    jitsi:
      loadBalancer:
        servers:
          - url: "http://hermes.lvk.sh:8000/"
    fdynmap:
      loadBalancer:
        servers:
          - url: "http://10.28.183.113:8123/"
  middlewares:
    sslRedirect:
      redirectScheme:
        scheme: https
        permanent: false
